config/routes.rb
UserNestedPath::Application.routes.draw do

  get "users_edit", :to => "users_batch#users_edit"

  post "users_post", :to => "users_batch#users_post"

  resources :users do
    resources :posts
  end

  root :to => 'users#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  before_save :set_next_user_post_id
  belongs_to :user
  
  validates :user_post_id, :uniqueness => {:scope => :user_id}

  def to_param
    self.user_post_id.to_s
  end

private
  def set_next_user_post_id
    self.user_post_id ||= get_new_user_post_id
  end

  def get_new_user_post_id
    user = self.user
    max = user.posts.maximum('user_post_id') || 0
    max + 1
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  accepts_nested_attributes_for :posts
end

app/models/user_set.rb
class UserSet
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :users

  def users_attributes=(attributes)
    # I'm tricking "fields_for" here.
    # This should never actually be called
    raise
  end

  def make_some_posts
    self.users.each {|user| user.posts.build}
  end

  # Strip fields_for indexes and return an array
  def self.users_from(user_set_hash)
    user_set_hash[:users_attributes].values
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :xml

  before_filter :find_user

  def index
    @posts = @user.posts.all
    respond_with @posts
  end

  def show
    @post = @user.posts.where(:user_post_id => (params[:id])).first
    respond_with [@user, @post]
  end

  def new
    @post = @user.posts.new
    respond_with [@user, @post]
  end

  def edit
    @post = @user.posts.where(:user_post_id => (params[:id])).first
    respond_with [@user, @post]
  end

  def create
    @post = @user.posts.new(params[:post])
    if @post.save
      flash[:notice] = "Successfully created post."
      respond_with [@user, @post]
    else
      respond_with @post
    end
  end

  def update
    @post = @user.posts.where(:user_post_id => (params[:id])).first
    if @post.update_attributes(params[:post])
      flash[:notice] = "Successfully updated post."
      respond_with [@user, @post]
    else
      respond_with @post
    end
  end

  def destroy
    @post = @user.posts.where(:user_post_id => (params[:id])).first
    @post.destroy
    respond_with [@user, @post]
  end
end

private
  def find_user
    @user = User.find(params[:user_id])
  end

app/controllers/users_batch_controller.rb
class UsersBatchController < ApplicationController
  def users_edit
    @user_set = UserSet.new
    @user_set.users = User.all

    # Add a new user
    @user_set.users << User.new

    # Make some dummy blank unsaved posts
    @user_set.make_some_posts

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def users_post
    @users = UserSet.users_from(params[:user_set])

    # Create your implementation to save HERE
    raise "#{@users.join("\n")}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_batch_helper.rb
module UsersBatchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserNestedPath</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', user_post_path(@user, @post) %> |
<%= link_to 'Back', user_path(@user) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Text</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.text %></td>
    <td><%= post.user.name %></td>
    <td><%= link_to 'Show', user_post_path(@user, post) %></td>
    <td><%= link_to 'Edit', edit_user_post_path(@user, post) %></td>
    <td><%= link_to 'Destroy', user_post_path(@user, post), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_user_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>

<p>
  <b>User:</b>
  <%= @post.user.name %>
</p>


<%= link_to 'Edit', edit_user_post_path(@post) %> |
<%= link_to 'Back', user_path(@user) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <% @user.posts.each do |post| %>
      <%= link_to "Post ##{post.user_post_id}", user_post_path(@user, post) %><br />
  <% end %>
</p>

<p>
  <%= link_to "Create new post", new_user_post_path(@user) %> 
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users_batch/_form.html.erb
<%= form_for @user_set, :url => '/users_post' do |l| %>

  <%= l.fields_for :users do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <%= f.fields_for :posts do |p| %>
      <%= p.text_area :text %>
    <% end %>
  <% end %>
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/users_batch/users_edit.html.erb
<h1>Editing users</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>